### ISSUE TITLE
Reboot Option

### ISSUE THREAD

**Issue by raspz1** [Schroedingers-Hat/Huawei-K4203#1]
Hey,
Your API is awesome!

Any chance of including the reboot command?

Thanks for all your great work :)

**Comment by Schroedingers-Hat** [comment]
Thanks. I don't have a modem with me right now. Are you able to open the network tab in chrome/firefox for me and reboot one via the web interface (I don't even remember if there was a button for this), capturing the request?

**Comment by raspz1** [comment]
Hey,

I don't have one with me right now either - but i can do it in a couple days when I return home :)

On mine, there was a button for reboot (either standard or to factory default) under settings > device controls

I will do it when I return home!

**Comment by raspz1** [comment]
Hi Schroedingers-Hat,

Here is the HAR file.
[modem reboot.har.zip](https://github.com/Schroedingers-Hat/Huawei-K4203/files/1664460/modem.reboot.har.zip)

I recorded only the standard reboot function.

From what I can see it POST to: http://192.168.9.1/api/device/control
with a token and <request><Control>1</Control>

Hope I did that right - lemme know!

**Comment by Schroedingers-Hat** [comment]
Thanks for the PR. Apologies on not getting back to you.
